apiVersion: v1
kind: PersistentVolume
metadata:
  name: ahyehaprod-backup-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ahyehaprod-backup-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: InnoDBCluster
metadata:
  name: mysql-clst
  namespace: ahyeha-prod
spec:
  instances: 3
  router:
    instances: 1
  secretName: myclsrootpwd
  tlsUseSelfSigned: true
  backupProfiles:       
  - name: ahyehaprodprofile  # Embedded backup profile
    dumpInstance:         # MySQL Shell Dump
      dumpOptions:
        excludeTables: #"[world.country]" # Example to exclude one table 
      storage:
        persistentVolumeClaim:
          claimName: ahyehaprod-backup-pvc # store to this pre-existing PVC
      backupSchedules:
        - name: ahyehaprodschedule
          schedule: "0 0 * * *" # Daily, at midnight
          backupProfileName:  ahyehaprodfrofile # reference the desired backupProfiles's name 
          enabled: true # backup schedules can be temporarily disabled
