apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: ahyeha-prod
  name: mysql-cls
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  schedule: {{ .Values.schedule }}
  successfulJobsHistoryLimit: 0 
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            draft: {{ default "draft-app" .Values.draft }}
            app: {{ .Chart.Name }} 
        spec:       
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }} 
            args:
              - sh
              - -c
              - |
                sleep 2 
                "/opt/myapp/myscript.sh"
                sleep 30
            env: 
              - name: APP_SECRET
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.appsecret }}
                    key: app_secret
              - name: APP_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.appsecret }}
                    key: app_client_id 
            ports:
            - containerPort: {{ .Values.service.internalPort }} 
          restartPolicy: {{ .Values.restartPolicy }}
          imagePullSecrets:
            - name: artifactory
