apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mycluster
spec:
  instances: 3
  router:
    instances: 1
  secretName: myclsrootpwd
  tlsUseSelfSigned: true
  backupProfiles:       
  - name: ahyehaprodprofile  # Embedded backup profile
    dumpInstance:         # MySQL Shell Dump
      dumpOptions:
        excludeTables: #"[world.country]" # Example to exclude one table 
      storage:
        persistentVolumeClaim:
          claimName: ahyehaprod-backup-pvc # store to this pre-existing PVC
      backupSchedules:
        - name: ahyehaprodschedule
          schedule: "0 0 * * *" # Daily, at midnight
          backupProfileName:  ahyehaprodfrofile # reference the desired backupProfiles's name 
          enabled: true # backup schedules can be temporarily disabled
